### ISSUE TITLE
Protocol typings: Challenges and SearchState interfaces are swapped

### ISSUE THREAD

**Issue by taylorhansen** [pkmn/ps#7]
Hi, I'm writing a PS bot that needs to respond to battle challenges. Looking through the `@pkmn/protocol` typings, I come across these two interfaces:

https://github.com/pkmn/ps/blob/c615c869dbb8587541121fd911b6bd03f3ef2e4d/protocol/src/index.ts#L244-L247

https://github.com/pkmn/ps/blob/c615c869dbb8587541121fd911b6bd03f3ef2e4d/protocol/src/index.ts#L271-L274

It seems that these two JSON interfaces have their contents swapped? A fix for this would be appreciated.

**Comment by scheibo** [comment]
Yup, I think you're right. Thanks for pointing this out, this will be fixed in the release cut tomorrow after the June 1 tier shifts land upstream.
